spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
spring.social.facebook.app-id: 772912672844150
spring.social.facebook.app-secret: c26d31cd4e5c690b7849f74b8e0bbd21

logging.level.me.south10.blog: DEBUG
#    jpa:
#        database: H2


#    datasource:
#        url: jdbc:h2:mem:mydb
#        username: sa
#        password: sa
#        driverClassName: org.h2.jdbcx.JdbcDataSource
#        platform: h2